---
- name: Installing the webservers
  hosts: docker
  become: true
  tasks:
    - name: installing package
      ansible.builtin.package:
        name: apache2
        state: latest

    - name: start the service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: modifying the webpage
      ansible.builtin.copy:
        content: |
          "Hello Learners!! Welcome to Path4cloud
           I am web server deployed via Ansible"
        dest: /var/www/html/index.html

- name: Testing the web server
  hosts: localhost
  become: true
  tasks:
    - name: testing....
      ansible.builtin.uri:
        url: http://192.168.139.9
        return_content: true
      register: webpage
      
    - name: Display page content
      ansible.builtin.debug:
        var: webpage.content